#!/bin/bash

dat=$(date +"%Y-%m-%d-%Hh%Mm%Ss")

if [ "$1" == "m" ]; then
    echo ""
    echo "Backup of current active model to github!"
    echo ""

    cp /home/manuel/.kde4/share/apps/simond/models/default/active/active.sbm /mnt/data/voxforge/nEW/GIT/LinJarK/others/
    exit
fi


echo ""
echo "use 'e' parameter to backup to external hdd!!"
echo ""

cd ~

cd .kde4/share/apps/simon/model/

XZ_OPT=-9

tar cfJ Simon_training.data.archive.tar.xz training.data/ prompts

mv Simon_training.data.archive.tar.xz Simon_training.data.archive_$dat.tar.xz

if [ "$1" == "e" ]; then
    echo ""
    echo "Moving backup to external HDD!"
    echo ""
    mv Simon_training.data.archive_$dat.tar.xz /run/media/manuel/bea5b975-3643-48ae-b0e3-9157b0905250/BACKUP/
else

mv Simon_training.data.archive_$dat.tar.xz /mnt/data

echo "moved archive to /mnt/data"

fi




echo "done"