#!/bin/bash

cd ~/.kde4/share/apps/simon/model

cd training.data

ls -1 | sed 's/.wav//g' | sed 's/$/ "default" /' > ../1.txt

ls -1 | sed 's/.wav//g' | awk -F '_S[0-9]+_.*$' '{print $1}' | sed 's/_/ /g' | awk '{print toupper($0)}' > ../2.txt

cd ..

paste 1.txt 2.txt > 3.txt

cat 3.txt | sed 's/\t//g' > prompts

rm 1.txt
rm 2.txt
rm 3.txt
