#!/bin/bash

cat $1/*.scenario | sed -n -e '/page/,$p' | sed '/trainingtext name/,+1 d' | sed 's/<[^>]*>//g' | sed '/^\s*$/d' | sed -e 's/^[ \t]*//' > $1/Linjark_Befehle_$1


tar czf linjark_$1_mod_pi_desk.tar.gz $1/.linjark/ $1/* 
