#!/bin/bash

cd $1

name=$(echo $1 |sed 's/\///g')

cat *.scenario | sed -n -e '/page/,$p' | sed '/trainingtext name/,+1 d' | sed 's/<[^>]*>//g' | sed '/^\s*$/d' | sed -e 's/^[ \t]*//' > Linjark_Befehle_$name


tar -jcvf ../linjark_"$name"_mod_pi_desk.tar.bz2 .linjark * 